---
- name: stop kubelet & docker daemon
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - kubelet
    - docker
  ignore_errors: true

- name: remove repos
  file:
    path: /etc/yum.repos.d/{{ item }}
    state: absent
  with_items:
    - aliyun.repo
    - daocloud.repo
    - docker-ce.repo
    - dce_offline.repo

- name: uninstall kubelet-{{ kubelet_version }} & docker-ce-{{ docker_version }}
  yum: 
    name: "{{ item }}"
    state: absent
  with_items:
    - kubelet-{{ kubelet_version }}
    - docker-ce-{{ docker_version }}

- name: filter mounted container dirs
  shell: df
  register: df_result

- set_fact: DF_RESULT={{ df_result.stdout | regex_findall('(/var/lib/kubelet/pods/.+)') }}
- name: unmount left pods 
  mount:
    path: "{{ item }}"
    state: unmounted
  with_items: "{{ DF_RESULT }}"

- name: clear kubelet & docker left directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/docker
    - /var/lib/dockershim
    - /var/lib/docker
    - /etc/kubelet
    - /etc/systemd/system/kubelet.service.d
    - /var/lib/kubelet
    - /usr/local/bin/kubectl
    - /var/local/dce
    - /usr/local/bin/dce-installer
    - /usr/bin/dce-installer


- name: thinpool
  lvol:
    vg: "{{ VG_NAME }}"
    lv: "{{ THINPOOL_NAME }}"
    state: absent
    force: "{{ force_remove | default('no') }}"
  ignore_errors: true
  tags: thinpool_remove

- name: vg
  lvg:
    vg: "{{ VG_NAME }}"
    state: absent
    force: "{{ force_remove | default('no') }}"
  ignore_errors: true
  tags: vg_remove

- name: Read device information (always use unit when probing)
  parted: device={{ THINPOOL_DISKS }} unit=MiB
  register: thinpool_disk_info
  ignore_errors: true

- name: Remove all partitions from disk
  parted:
    device: "{{ THINPOOL_DISKS }}"
    number: "{{ item.num }}"
    state: absent
  with_items:
    - "{{ thinpool_disk_info.partitions }}"
  tags: pv_remove
  ignore_errors: true

- name: uninstall dce depends
  yum: 
    name: "{{ item }}"
    state: absent
  with_items:
    - wget
    - bind-utils
    - iptables-services
    - bash-completion
    - sos
    - psacct
    - chrony
    - audit
    - systemd-journal-gateway
    - socat
    - ipvsadm

- import_tasks: ntp_uninstall.yml
  tags: ntp
