- name: clear containers stopped 
  cron:
    name: "clear containers stopped"
    minute: "0"
    hour: "4"
    job: "docker container prune -f"

- name: clear images <none>
  cron:
    name: "clear images <none>"
    minute: "0"
    hour: "6"
    job: docker rmi $(docker images|awk '{NR>1;if ($1=="<none>" || $2=="<none>"){print $3}}')

